name=oracle-custom
connector.class=lab.OraclePollingSourceConnector
tasks.max=1
connection.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
connection.user=KAFKA_CUSTOM
connection.password=custom_reader
topic=custom.connect.orders
batch.max.rows=2
poll.interval.ms=1000
timestamp.delay.interval.ms=5000
