bootstrap.servers=localhost:9092
listeners=http://127.0.0.1:8085
rest.advertised.host.name=localhost
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
offset.storage.file.filename=state/connect-offsets.bin
offset.flush.interval.ms=1000
plugin.discovery=only_scan
topic.creation.enable=false
producer.acks=all
producer.enable.idempotence=true
