WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO ON
ALTER SESSION SET CONTAINER=XEPDB1;
DECLARE
    n NUMBER;
BEGIN
    SELECT COUNT(*) INTO n FROM DBA_USERS WHERE USERNAME = 'APP';
    IF n = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER APP IDENTIFIED BY app DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    END IF;
END;
/
GRANT CREATE SESSION, CREATE TABLE TO APP;
DECLARE
    n NUMBER;
BEGIN
    SELECT COUNT(*) INTO n FROM DBA_TABLES WHERE OWNER = 'APP' AND TABLE_NAME = 'ORDERS';
    IF n = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE APP.ORDERS
            (ID NUMBER(18, 0) NOT NULL PRIMARY KEY, STATUS VARCHAR2(50), AMOUNT NUMBER(12, 2), UPDATED_AT TIMESTAMP(6) NOT NULL)';
    END IF;
    SELECT COUNT(*) INTO n FROM DBA_INDEXES WHERE OWNER = 'APP' AND INDEX_NAME = 'IDX_ORDERS_CURSOR';
    IF n = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX APP.IDX_ORDERS_CURSOR ON APP.ORDERS (UPDATED_AT, ID)';
    END IF;
END;
/
EXIT;
