WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO ON
SELECT SYS_CONTEXT('USERENV','CON_NAME') AS CONTAINER_NAME FROM DUAL;
SELECT COLUMN_NAME,DATA_TYPE,NULLABLE FROM USER_TAB_COLUMNS WHERE TABLE_NAME='ORDERS' ORDER BY COLUMN_ID;
SELECT * FROM ORDERS ORDER BY ID;
EXIT;
