WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO ON
ALTER SESSION SET CONTAINER=XEPDB1;
DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM DBA_USERS WHERE USERNAME='KAFKA_CUSTOM';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE USER KAFKA_CUSTOM IDENTIFIED BY custom_reader'; END IF;
END;
/
GRANT CREATE SESSION TO KAFKA_CUSTOM;
GRANT SELECT ON APP.ORDERS TO KAFKA_CUSTOM;
SELECT GRANTEE,PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE='KAFKA_CUSTOM';
SELECT GRANTEE,OWNER,TABLE_NAME,PRIVILEGE FROM DBA_TAB_PRIVS WHERE GRANTEE='KAFKA_CUSTOM';
EXIT;
