FROM confluentinc/cp-kafka-connect:7.7.1
USER root
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.8.0
RUN curl -fSL --retry 3 https://repo.maven.apache.org/maven2/com/oracle/database/jdbc/ojdbc11/23.3.0.23.09/ojdbc11-23.3.0.23.09.jar \
    -o /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/ojdbc11.jar
USER 1000
