WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO ON
-- Run only when V$DATABASE.LOG_MODE is NOARCHIVELOG, before starting workers.
ALTER SESSION SET CONTAINER=CDB$ROOT;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1='LOCATION=/opt/oracle/oradata/archive' SCOPE=BOTH;
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
DECLARE m VARCHAR2(20);
BEGIN
  SELECT OPEN_MODE INTO m FROM V$PDBS WHERE NAME='XEPDB1';
  IF m <> 'READ WRITE' THEN EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE XEPDB1 OPEN'; END IF;
END;
/
ALTER PLUGGABLE DATABASE XEPDB1 SAVE STATE;
ARCHIVE LOG LIST;
EXIT;
