WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO ON
ALTER SESSION SET CONTAINER=CDB$ROOT;
DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM V$DATABASE WHERE SUPPLEMENTAL_LOG_DATA_MIN='NO';
  IF n>0 THEN EXECUTE IMMEDIATE 'ALTER DATABASE ADD SUPPLEMENTAL LOG DATA'; END IF;
END;
/
ALTER SESSION SET CONTAINER=XEPDB1;
DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM DBA_LOG_GROUPS WHERE OWNER='APP' AND TABLE_NAME='ORDERS' AND LOG_GROUP_TYPE='ALL COLUMN LOGGING';
  IF n=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE APP.ORDERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS'; END IF;
END;
/
EXIT;
