WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO ON
ALTER SESSION SET CONTAINER=CDB$ROOT;
DECLARE n NUMBER;
BEGIN
 SELECT COUNT(*) INTO n FROM DBA_TABLESPACES WHERE TABLESPACE_NAME='LOGMINER_TBS';
 IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLESPACE LOGMINER_TBS DATAFILE ''/opt/oracle/oradata/logminer-root.dbf'' SIZE 25M AUTOEXTEND ON MAXSIZE 256M'; END IF;
END;
/
ALTER SESSION SET CONTAINER=XEPDB1;
DECLARE n NUMBER;
BEGIN
 SELECT COUNT(*) INTO n FROM DBA_TABLESPACES WHERE TABLESPACE_NAME='LOGMINER_TBS';
 IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLESPACE LOGMINER_TBS DATAFILE ''/opt/oracle/oradata/logminer-pdb.dbf'' SIZE 25M AUTOEXTEND ON MAXSIZE 256M'; END IF;
END;
/
ALTER SESSION SET CONTAINER=CDB$ROOT;
DECLARE n NUMBER;
BEGIN
 SELECT COUNT(*) INTO n FROM DBA_USERS WHERE USERNAME='C##DBZUSER';
 IF n=0 THEN EXECUTE IMMEDIATE 'CREATE USER C##DBZUSER IDENTIFIED BY dbz DEFAULT TABLESPACE LOGMINER_TBS QUOTA UNLIMITED ON LOGMINER_TBS CONTAINER=ALL'; END IF;
END;
/
GRANT CREATE SESSION, SET CONTAINER TO C##DBZUSER CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE, SELECT ANY TABLE, SELECT ANY TRANSACTION TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE, EXECUTE_CATALOG_ROLE, LOGMINING TO C##DBZUSER CONTAINER=ALL;
GRANT CREATE TABLE, LOCK ANY TABLE, CREATE SEQUENCE TO C##DBZUSER CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR TO C##DBZUSER CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$MYSTAT TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$STATNAME TO C##DBZUSER CONTAINER=ALL;

EXIT;
