WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO ON
ALTER SESSION SET CONTAINER=CDB$ROOT;
SELECT LOG_MODE,SUPPLEMENTAL_LOG_DATA_MIN FROM V$DATABASE;
ALTER SYSTEM SWITCH LOGFILE;
ALTER SYSTEM ARCHIVE LOG CURRENT;
SELECT DEST_ID,STATUS,TYPE,DESTINATION,ERROR FROM V$ARCHIVE_DEST_STATUS WHERE STATUS='VALID';
SELECT NAME FROM V$ARCHIVED_LOG WHERE NAME IS NOT NULL ORDER BY SEQUENCE# DESC FETCH FIRST 3 ROWS ONLY;
SELECT GRANTEE,PRIVILEGE,COMMON FROM DBA_SYS_PRIVS WHERE GRANTEE='C##DBZUSER' ORDER BY PRIVILEGE;
ALTER SESSION SET CONTAINER=XEPDB1;
SELECT OWNER,TABLE_NAME,LOG_GROUP_TYPE FROM DBA_LOG_GROUPS WHERE OWNER='APP' AND TABLE_NAME='ORDERS';
EXIT;
