WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO ON
-- Change 100 in all demo files if this ID is already used.
INSERT INTO ORDERS VALUES (100,'INSERTED',10,CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS TIMESTAMP));
COMMIT;

EXIT;
