WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO ON
UPDATE ORDERS SET STATUS='UPDATED',AMOUNT=20,UPDATED_AT=CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS TIMESTAMP) WHERE ID=100;
COMMIT;

EXIT;
