WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO ON
INSERT INTO ORDERS VALUES (101,'ROLLBACK',99,CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS TIMESTAMP));
ROLLBACK;
SELECT * FROM ORDERS WHERE ID=101;

EXIT;
